import { defineField, defineType } from "sanity";

export default defineType({
  name: "project",
  title: "Projects",
  type: "document",
  fields: [
    defineField({
      name: "title",
      title: "Project Title",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "subtitle",
      title: "Subtitle",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: {
        source: "title",
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "tagline",
      title: "Tagline",
      type: "string",
      description: "Short one-liner about the project",
      validation: (Rule) => Rule.max(150),
    }),
    defineField({
      name: "coverImage",
      title: "Cover Image",
      type: "image",
      options: {
        hotspot: true,
      },
      fields: [
        {
          name: "alt",
          type: "string",
          title: "Alternative Text",
          description: "Describe the image for accessibility",
        },
      ],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "technologies",
      title: "Technologies Used",
      type: "array",
      of: [{ type: "reference", to: [{ type: "skill" }] }],
      description: "Select from your skills list (max 6 recommended)",
      validation: (Rule) => Rule.max(8),
    }),
    defineField({
      name: "categories",
      title: "Project Categories",
      type: "array",
      of: [
        {
          type: "string",
          options: {
            list: [
              { title: "Web Application", value: "web-app" },
              { title: "Business Website", value: "business-website" },
              { title: "Website", value: "website" },
              { title: "Web Scraping", value: "web-scraping" },
              { title: "MERN", value: "mern" },
              { title: "MEAN", value: "mean" },
              { title: "PERN", value: "pern" },
              { title: "AWS", value: "aws" },
              { title: "Microservices", value: "microservices" },
              { title: "Full-Stack", value: "full-stack" },
              { title: "Learning Platforms / EdTech Systems", value: "learning-platforms-ed-tech-systems" },
              { title: "Mobile App", value: "mobile-app" },
              { title: "Medical", value: "medical" },
              { title: "Healthcare", value: "healthcare" },
              { title: "Dental", value: "dental" },
              { title: "Real Estate", value: "realestate" },
              { title: "Travel", value: "travel" },
              { title: "Fitness", value: "fitness" },
              { title: "Fintech", value: "fintech" },
              { title: "Food Delivery", value: "food-delivery" },
              { title: "SMS Notification", value: "sms-notification" },
              { title: "CMS", value: "cms" },
              { title: "LMS", value: "lms" },
              { title: "PMS", value: "pms" },
              { title: "ERP", value: "erp" },
              { title: "IMS", value: "ims" },
              { title: "AI ML", value: "aiml" },
              { title: "AI Powered", value: "ai-powered" },
              { title: "IDE/ADE", value: "ideade" },
              { title: "Auth", value: "auth" },
              { title: "Social Media", value: "social-media" },
              { title: "Instant Messaging", value: "instant-messaging" },
              { title: "Video Chat", value: "video-chat" },
              { title: "File Downloading", value: "file-downloading" },
              { title: "File Uploading", value: "file-uploading" },
              { title: "Operating Systems", value: "operatingsystems" },
              { title: "APIs", value: "apis" },
              { title: "Mapping", value: "mapping" },
              { title: "API/Backend", value: "api-backend" },
              { title: "DevOps/Infrastructure", value: "devops" },
              { title: "Open Source", value: "open-source" },
              { title: "CLI Tool", value: "cli-tool" },
              { title: "Desktop App", value: "desktop-app" },
              { title: "Browser Extension", value: "browser-extension" },
              { title: "Game", value: "game" },
              { title: "Ecommerce", value: "ecommerce" },
              { title: "Platform", value: "platform" },
              { title: "SaaS", value: "saas" },
              { title: "Other", value: "other" },
            ],
          },
        },
      ],
      description: "Select one or more categories for this project",
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: "liveUrl",
      title: "Live URL",
      type: "url",
      description: "Link to the live project",
    }),
    defineField({
      name: "githubUrl",
      title: "GitHub URL",
      type: "url",
      description: "Link to the GitHub repository",
    }),
    defineField({
      name: "featured",
      title: "Featured Project",
      type: "boolean",
      description: "Show this project prominently on the homepage",
      initialValue: false,
    }),
    defineField({
      name: "order",
      title: "Display Order",
      type: "number",
      description: "Lower numbers appear first (0-99)",
      initialValue: 0,
      validation: (Rule) => Rule.min(0).max(99),
    }),
  ],
  preview: {
    select: {
      title: "title",
      media: "coverImage",
      categories: "categories",
      featured: "featured",
    },
    prepare(selection) {
      const { title, media, categories, featured } = selection;
      const categoryText = categories?.length ? categories.join(", ") : "Uncategorized";
      return {
        title: featured ? `⭐ ${title}` : title,
        subtitle: categoryText,
        media: media,
      };
    },
  },
  orderings: [
    {
      title: "Display Order",
      name: "orderAsc",
      by: [{ field: "order", direction: "asc" }],
    },
    {
      title: "Featured First",
      name: "featuredFirst",
      by: [
        { field: "featured", direction: "desc" },
        { field: "order", direction: "asc" },
      ],
    },
  ],
});
